<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>top.continew.starter</groupId>
        <artifactId>continew-starter</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>continew-starter-storage</artifactId>
    <packaging>jar</packaging>

    <name>${project.artifactId}</name>
    <description>ContiNew Starter 存储模块</description>

    <dependencies>
        <!-- 核心模块 -->
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>continew-starter-core</artifactId>
        </dependency>

        <!-- Amazon S3 V2（Amazon Simple Storage Service，亚马逊简单存储服务，通用存储协议 S3，兼容主流云厂商对象存储） -->
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>s3</artifactId>
        </dependency>

        <!-- 缩略图生成库 -->
        <dependency>
            <groupId>net.coobird</groupId>
            <artifactId>thumbnailator</artifactId>
        </dependency>

        <!-- JSON 模块 - Jackson -->
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>continew-starter-json-jackson</artifactId>
        </dependency>
    </dependencies>
</project>