--- ### 开放 API 配置
openapi:
  # 应用 ID 参数名
  app-id-param-name: appId
  # 签名参数名
  sign-param-name: sign
  # 随机字符串参数名
  nonce-param-name: nonce
  # 时间戳参数名
  timestamp-param-name: timestamp
  # 是否启用 nonce 防重放
  nonce-enabled: true
  # 时间戳允许差距时间（默认 15 分钟，-1 代表不校验差距）
  timestamp-disparity-in-millis: 900000
  # 默认签名算法
  default-algorithm: MD5
