CREATE TABLE IF NOT EXISTS t_user (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       name VARCHAR(255) NOT NULL,
                                       age INT,
                                       email VARCHAR(255) UNIQUE
);


