<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>top.continew.starter</groupId>
        <artifactId>continew-starter-encrypt</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>continew-starter-encrypt-password-encoder</artifactId>
    <packaging>jar</packaging>

    <name>${project.artifactId}</name>
    <description>ContiNew Starter 加密模块 - 密码编码器</description>

    <dependencies>
        <!-- 加密模块 - 核心模块 -->
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>continew-starter-encrypt-core</artifactId>
        </dependency>

        <!-- Spring Security 附带的一个密码加密库 -->
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-crypto</artifactId>
        </dependency>
    </dependencies>
</project>