name: "\U0001F41E 报告 Bug/Bug Report"
description: 帮助我们更好地改进项目，但请先阅读官方文档及常见问题，不要提已有的重复问题！/Create a report to help us improve, please read FAQ first.
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        感谢您使用 ContiNew Starter！请您花些时间填写这份 Bug 报告。ContiNew Admin 项目 Bug 请提交至 [ContiNew Admin](https://github.com/continew-org/continew-admin/issues/new/choose)。<br>
        **温馨提示：我们利用业余时间维护开源项目，没有额外精力及人员维护已发布版本，所以请务必检查【最新版本】是否正常，如已修复请自行跟进修复！**
  - type: checkboxes
    id: checkboxes
    attributes:
      label: 请您确认
      description: 在提交 Bug 之前，请先确认 :)
      options:
        - label: 我确认重启过项目和 IDE 后，仍然能够复现此问题
          required: true
        - label: 我确认尝试了 [最新版本](https://central.sonatype.com/artifact/top.continew.starter/continew-starter/versions)（也可 mvn install dev 分支的最新 SNAPSHOT 版本测试，但生产请等待下个发布版），仍有相同问题
          required: true
        - label: 我确认搜索了 [Issue 广场](https://continew.top/docs/starter/issue-hub.html)，没有其他人提交过类似的 Bug（如果对应 Bug 尚未解决，您可以先订阅关注该 Issue，为了方便后来者查找问题解决方法，请避免创建重复的 Issue）
          required: true
        - label: 我确认查阅过 [使用指南](https://continew.top/docs/starter/guide/introduction.html) 和 [常见问题](https://continew.top/docs/starter/faq.html)
          required: true
        - label: 我确认问过 [DeepWiki](https://deepwiki.com/continew-org/continew-starter) 及知名 AI 大模型
          required: true
        - label: 我尝试阅读了源码并在 IDE 中进行断点调试
          required: false
        - label: 我愿意为提出的 Bug 提交 PR 修复它
          required: false
        - label: 请不要修改此模板 :) 并填写所有必填字段
          required: true
    validations:
      required: true

  - type: dropdown
    attributes:
      label: ContiNew Starter 版本
      description: 您使用的 ContiNew Starter 版本，如没有支持的版本选项，请查阅 [更新日志](https://continew.top/docs/starter/changelog/) 并升级至最新稳定版本。
      multiple: false
      options:
        - 2.16.0-SNAPSHOT (开发版本-dev 分支)
        - 2.15.1
        - 2.15.0
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug 描述
      description: 清楚而简洁地描述您遇到的 Bug。
      placeholder: 例如：在使用 xxx 功能时出现异常
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: 复现步骤
      description: 强烈建议附上截图和完整错误日志！代码块请使用正确的 Markdown 格式。
      placeholder: 详细的步骤有助于我们复现问题。如有日志，请使用代码块格式（三个反引号 ```），如截图中存在敏感信息，请注意添加马赛克脱敏。
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 预期结果
      description: 清楚而简洁地描述您期望的结果。
      placeholder: 你期望的是什么？请不要在这里复制粘贴复现步骤。
    validations:
      required: true

  - type: textarea
    id: environment-info
    attributes:
      label: 环境信息
      description: 添加一切能帮助定位问题的环境信息。
      placeholder: 例如：JDK 版本：17，Maven 版本：3.6.3
    validations:
      required: false