name: "\U00002728 期望新增功能/Feature Request"
description: 期望新增什么样的功能或特性，或者做哪些方面的改进？/Suggest an enhancement or new feature.
labels:
  - feature
body:
  - type: markdown
    attributes:
      value: |
        感谢您使用 ContiNew Starter！请您花些时间填写这份 Feature 调查。ContiNew Admin 项目 Feature 请提交至 [ContiNew Admin](https://github.com/continew-org/continew-admin/issues/new/choose)。<br>
        **温馨提示：我们利用业余时间维护开源项目，没有额外精力及人员开发特定业务功能，如业务仅为小众需求，请确认是否有必要提交！**
  - type: checkboxes
    id: checkboxes
    attributes:
      label: 请您确认
      description: 在提交 Feature 之前，请先确认 :)
      options:
        - label: 我确认尝试了 [最新版本](https://central.sonatype.com/artifact/top.continew/continew-starter/versions)（还可以尝试本地编译安装 dev 分支的最新快照版本），仍没有该功能
          required: true
        - label: 我确认查阅过 [使用指南](https://continew.top/docs/starter/guide/introduction.html) 和 [常见问题](https://continew.top/docs/starter/faq.html) ，仍然认为很有必要
          required: true
        - label: 我确认搜索了 [Issue 广场](https://continew.top/docs/starter/issue-hub.html)，没有其他人提交过类似的 Feature（如果对应 Feature 尚未实现，您可以先订阅关注该 Issue，为了方便后来者查找问题解决方法，请避免创建重复的 Issue）
          required: true
        - label: 我愿意为提出的 Feature 提交 PR 实现它
          required: false
        - label: 请不要修改此模板 :) 并填写所有必填字段
          required: true
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Feature 描述
      description: 清楚而简洁地描述您的 Feature。
      placeholder: 例如：我希望增加 xxx 功能；现有的 xxx 功能不好用...
    validations:
      required: true

  - type: textarea
    id: suggested-solution
    attributes:
      label: 描述一下您想要的解决方案
      description: 清楚而简洁地描述您想要的解决方案。
    validations:
      required: true

  - type: textarea
    id: alternative
    attributes:
      label: 描述一下您考虑过的替代方案
      description: 清楚而简洁地描述您考虑过的任何替代解决方案或功能。

  - type: textarea
    id: additional-context
    attributes:
      label: 额外补充
      description: 添加您在其他框架或场景遇见的效果截图或链接，以及一切能帮助理解 Feature 的信息。
