<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>top.continew.starter</groupId>
        <artifactId>continew-starter</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>continew-starter-ratelimiter</artifactId>
    <packaging>jar</packaging>

    <name>${project.artifactId}</name>
    <description>ContiNew Starter 限流模块</description>

    <dependencies>
        <!-- 核心模块 -->
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>continew-starter-core</artifactId>
        </dependency>

        <!-- 缓存模块 - Redisson -->
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>continew-starter-cache-redisson</artifactId>
        </dependency>
    </dependencies>
</project>
