<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>top.continew.starter</groupId>
        <artifactId>continew-starter-extension-tenant</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>continew-starter-extension-tenant-mp</artifactId>
    <packaging>jar</packaging>

    <name>${project.artifactId}</name>
    <description>ContiNew Starter 扩展模块 - 租户 - MyBatis Plus ORM</description>

    <dependencies>
        <!-- 租户 - 核心模块 -->
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>continew-starter-extension-tenant-core</artifactId>
        </dependency>

        <!-- MyBatis Plus jsqlparser 适配（包含原扩展模块内容） -->
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-jsqlparser</artifactId>
        </dependency>

        <!-- Dynamic Datasource（基于 Spring Boot 的快速集成多数据源的启动器） -->
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>dynamic-datasource-spring-boot3-starter</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>
</project>